### ISSUE TITLE
Can't build bruce in ubuntu 14.04

### ISSUE THREAD

**Issue by alecinvan** [ifwe/bruce#3]
Hi, 

I am build bruce in ubuntu

cd bruce
source bash_defs
cd src/bruce
build --release bruce
But getting error :
g++ -o out/release/bruce/debug/debug_setup.o -c -std=c++11 -Wold-style-cast -Wall -Wextra -Werror -O2 -DNDEBUG -Wno-unused -Wno-unused-parameter -flto -fvisibility=hidden -DSRC_ROOT='"/home/stuser/RESTClients/bruce/src"' -Isrc -Isrc/third_party/tclap-1.2.0/include src/bruce/debug/debug_setup.cc
src/bruce/debug/debug_setup.cc: In member function 'void Bruce::Debug::TDebugSetup::CreateDebugDir()':
src/bruce/debug/debug_setup.cc:175:32: error: format not a string literal and no format arguments [-Werror=format-security]
     syslog(LOG_ERR, msg.c_str());
                                ^
cc1plus: all warnings being treated as errors
scons: **\* [out/release/bruce/debug/debug_setup.o] Error 1

Any idea?

thanks

AL

**Comment by dspeterson** [comment]
Hi Al,

Thanks for the problem report.  I'll take a look at it, hopefully this weekend.

Dave

**Comment by alecinvan** [comment]
Thanks a lot, Dave.

**Comment by dspeterson** [comment]
I just added -Wformat=2, which enables -Wformat-security along with a few related warnings.  Since the build specifies -Werror, these warnings will be treated as errors.  I also enabled a few additional warnings and fixed the code so it compiles with the new warnings enabled.
