### ISSUE TITLE
Building specific version

### ISSUE THREAD

**Issue by sdowns** [ifwe/bruce#5]
When trying to build a specific version of the code (based on the tags) from Jenkins, the build version always gets the version closest to the head.

The line of code that appears to be doing this is in: src/bruce/scripts/gen_version
The line of code appears to be on line 132, below are lines 131 - 134:

```
131         try:
132             p = subprocess.Popen(['git', 'describe', 'master'],
133                                  stdout=subprocess.PIPE)
134             version, err = p.communicate()
```

Removing the 'master' parameter (as seen below) happens to solve the problem I'm seeing, but I'm not an expert in git.  It worked for building 1.0.12, and 1.0.16, as well as 1.0.17.

```
132             p = subprocess.Popen(['git', 'describe'],
```

When I made that change the build was able compile successfully and the version number of bruce output correctly when running "bruce --version".  Without the change, the version of bruce was always labeled as 1.0.17 even though the code base that was checked out (and therefore compiled) was 1.0.12 or 1.0.16.

**Comment by dspeterson** [comment]
Ok, thanks for the problem report.  I'll take a look this evening and get back to you shortly.

**Comment by dspeterson** [comment]
I just applied the fix you suggested.  Thanks!
